export const CONTAINER_FILL_VIDEOS = {
  1: { step: 1, file: "/videos/container_steps/step_01.mp4" },
  2: { step: 2, file: "/videos/container_steps/step_02.mp4" },
  3: { step: 3, file: "/videos/container_steps/step_03.mp4" },
  4: { step: 4, file: "/videos/container_steps/step_04.mp4" },
  5: { step: 5, file: "/videos/container_steps/step_05.mp4" },
  6: { step: 6, file: "/videos/container_steps/step_06.mp4" },
  7: { step: 7, file: "/videos/container_steps/step_07.mp4" },
  8: { step: 8, file: "/videos/container_steps/step_08.mp4" },
  9: { step: 9, file: "/videos/container_steps/step_09.mp4" },
  10: { step: 10, file: "/videos/container_steps/step_10.mp4" },
  11: { step: 11, file: "/videos/container_steps/step_11.mp4" },
  12: { step: 12, file: "/videos/container_steps/step_12.mp4" },
  13: { step: 13, file: "/videos/container_steps/step_13.mp4" },
  14: { step: 14, file: "/videos/container_steps/step_14.mp4" },
  15: { step: 15, file: "/videos/container_steps/step_15.mp4" },
  16: { step: 16, file: "/videos/container_steps/step_16.mp4" },
  17: { step: 17, file: "/videos/container_steps/step_17.mp4" },
  18: { step: 18, file: "/videos/container_steps/step_18.mp4" },
  19: { step: 19, file: "/videos/container_steps/step_19.mp4" },
  20: { step: 20, file: "/videos/container_steps/step_19.mp4" }, // Fallback to 19 for 20 until we get it
};
